### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Kiog-Aser** [hsnice16/forming-typeform#17]
Hi!

I have a few questions. First of all, can you actually submit the form data to some kind of spreadsheet?

Second of all, how could I change/ add questions (there's some weird logic going on there...)

Lastly, are there any tutorials on setting this project up for personal use?

Thanks!

**Comment by hsnice16** [comment]
> can you actually submit the form data to some kind of spreadsheet?

It should be possible, but it's not implemented in this project.
Reason: It was a take-home assignment that's why, :). You can [this](https://x.com/hsnice16/status/1753291666109399114?s=20) thread as well.

> how could I change/ add questions (there's some weird logic going on there...)

This will require some work.
- If you want to change questions, then you can check [question](https://github.com/hsnice16/forming-typeform/tree/main/components/question) folder in components. Make changes to the question you want.
- If you want to add a new question, then you will have to make changes in the question folder mentioned in the above point, and you would also need to make changes in the [main-content](https://github.com/hsnice16/forming-typeform/tree/main/components/main-content) folder. Today, the logic is that for any question, on DOM there should be only elements for that question and elements for questions before that and after that. So, you can make the changes accordingly.

> are there any tutorials on setting this project up for personal use?

Info present in [README.md](https://github.com/hsnice16/forming-typeform/blob/main/README.md) should be enough for this.

**Comment by hsnice16** [comment]
Hey @Kiog-Aser 
Let me know if you have any open questions, otherwise I will close this issue.
